# Report-specific parameters
template: plotTemplate.Rmd
templatePackage: clinDataReview
reportTitle: "Laboratory parameters: time profiles"
reportTitleLevel: 1
# Dataset of interest
dataFileName: lb.xpt
dataProcessing:
  - annotate:
    - dataset: dm
      vars: ["RFXSTDTC", "ARM"]
    - vars: LBCAT
      varFct: 'ifelse(LBCAT == "", "Not Coded", LBCAT)'
  - filter:
    # safety analysis set: treated-patients
    - var: "RFXSTDTC" 
      value: ""
      rev: true
# Looping parameters
loopingVar: ["LBTEST"]
# Plot parameters
plotFunction: "scatterplotClinData"
plotParams:
  xVar: "LBDY"
  yVar: "LBSTRESN"
  aesPointVar:
    colour: "ARM"
    fill: "ARM"
    shape: "LBNRIND"
  aesLineVar:
    group: "USUBJID"
  refLinePars:
    - yintercept: "LBSTNRLO"
      colour: "lightblue"
    - yintercept: "LBSTNRHI"
      colour: "darkblue"
  scalePars:
    - aesthetic: shape
      values: !r-lazy clinUtils::getPaletteCDISC(x = dataI$LBNRIND, var = "NRIND", type = "shape")
  themePars:
      legend.position: "none"
  hoverVars: ["USUBJID", "VISIT", "LBDY", "LBSTRESN", "LBNRIND", "LBSTNRLO", "LBSTNRHI"]
  tableVars: ["LBCAT", "LBTEST", "USUBJID", "VISIT", "LBDY", "LBSTRESN", "LBNRIND", "LBSTNRLO", "LBSTNRHI"]



